### ISSUE TITLE
Hunt for abuse of certutil

### ISSUE THREAD

**Issue by th3y3ti** [th3y3ti/poc-tahiti-wfms#7]
Fill in the following minimal information...

|Field|Value|
|-|-|
|**Author/Requester:**|Jone Doe|
|**Hypothesis**|Threat Actors are using certutil to dl malware|
|**Trigger:**|Intel|

**Acceptance Criteria**  
This issue can be closed when all of the tasks have been completed or this hunt is no longer needed.

**Tasks**
- [ ] Validate Detection Gap
- [ ] Validate Data Availability & Accessibility 
- [ ] Define/Refine Abstract
- [ ] Execute Hunt
- [ ] Document Findings
- [ ] Handover
